### ISSUE TITLE
reload.coffee not reloading scripts content

### ISSUE THREAD

**Issue by srobroek** [github/hubot-scripts#1475]
When using reload.coffee scripts (in either ./node_modules/src/scripts or ./scripts) are reloaded, but new content is not available until the hubot proces is stopped and started.

When testing this new scripts (as in - a new filename) are loaded, but when they have been loaded once they are not reloaded. Possibly invalidating the require.cache is needed.

**Comment by ileathan** [comment]
+100 @srobroek,

Should close this topic since its now fixed.. not sure why the maintainers have not merged.

**Comment by ileathan** [comment]
Hi I know its been 2 years but since i love this fix and just noticed that the reload script appends EventEmitter listeners Ill document this here.

If you have the following code

```
robot.on "test", (msg) ->
  msg.send "Hi"
```

It will append another event listener for "test" meaning your bot will send `Hi` twice. adding a check to see if the event already exists (in your script) before adding it fixes the problem, but obviously someone should fix the reload.coffee script directly, just lazy.

**Comment by technicalpickles** [comment]
This repo has been deprecated for awhile, so we won't be fixing this.
